config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/edit'

  get 'password_resets/update'

 root 'voyages#index'
 resources :user_sessions
 resources :users

 resources :voyages do
   resources :reservations
 end

 get 'login' => 'user_sessions#new', :as => :login
 delete 'logout' => 'user_sessions#destroy', :as => :logout

 resources :password_resets

end
#destroy', :as => :logout

app/models/voyage.rb
class Voyage < ApplicationRecord
  belongs_to :captain, class_name: 'User', foreign_key: 'captain_id'
  has_many :reservations
  has_many :passengers, through: :reservations

  geocoded_by :location
  after_validation :geocode

  has_attached_file :voyage_image_file, default_url: "missing.png"
  validates_attachment_content_type :voyage_image_file, content_type: /\Aimage\/.*\z/

  has_attached_file :boat_image_file, default_url: "missing.png"
  validates_attachment_content_type :boat_image_file, content_type: /\Aimage\/.*\z/


  validates :title, presence: true

  validates :location, presence: true

  validates :start_time, presence: true

  validates :end_time, presence: true

  validate :start_time_cannot_be_in_the_past

  #  validate :check_for_capacity?
   #validates capcity: if there is no space on boat then rollback reservation and display custom error.
  validates :capacity, presence: true

    def start_time_cannot_be_in_the_past #validation to make sure captains cannot create voyages in the past
     if start_time.present? && start_time < DateTime.now
       errors.add(:start_time, message: "You can't make a voyage in the past! Please try again.")
     end
   end

    validates :capacity, presence: true
    #
    # validates :capacity, numericality: true, { :greater_than => 0, :less_than_or_equal_to => 20 } #validates capacity to be an integer greater than or equal to 0

    validates_inclusion_of :capacity, in: 0..20

   def present_capacity
     self.capacity - self.reservations.count
   end

  #  def check_for_capacity?
  #    unless has_capacity?
  #      errors.add(:capacity, message: "Sorry, this trip is full. Choose another trip!")
  #    end
  #  end

   def has_capacity?
     present_capacity <= 0
   end

   def self.search(search)
    where("location LIKE ?", "%#{search}%")
  end

end

app/controllers/voyages_controller.rb
class VoyagesController < ApplicationController

  skip_before_action :require_login, only: [:index, :show]

  before_action do
    @user = User.find(params[:user_id]) if params[:user_id]
  end


  before_action :ensure_user_match, only: [:edit, :update, :delete]

  helper_method(:captain_is_user?)

  def index
    if @user
      @voyages = @user.voyages
    else
      @voyages = Voyage.all
      if params[:search]
         @voyages = Voyage.search(params[:search])
        #  .order("created_at DESC")
      #  else
      #    @voyages = Voyage.all
        #  .order('created_at DESC')
       end
    end


  end

  def show
    @reservation = Reservation.new
    @voyage = Voyage.find(params[:id])
    # # this is gmaps code from tutorial gmaps4rails
    # binding.pry
    # @hash = Gmaps4rails.build_markers(@voyages) do |voyage, marker|
    #   marker.lat voyage.latitude
    #   marker.lng voyage.longitude
    # end
  end

  def edit
    @voyage = Voyage.find(params[:id])
  end

  def update
    @user = User.find(current_user)
    @voyage = Voyage.find(params[:id])
    if @voyage.update(voyage_params)
      redirect_to @user
      flash[:Success] = ": Voyage succesfully changed."
    else
      redirect_to @user
      flash[:notice] = "Voyage was not updated."
    end
  end

  def new
    @voyage = Voyage.new
  end

  def create
    @voyage = Voyage.new(voyage_params)
    @voyage.captain = current_user

      if @voyage.save
        redirect_to @voyage
          flash[:notice] = "Voyage succesfully created."
      else
          flash[:notice] = @voyage.errors.full_messages
        redirect_to new_voyage_path
      end

    # respond_to

  end

  def destroy
    @voyage = Voyage.find(params[:id])
    @voyage.destroy
    redirect_to current_user
  end

  #edit needs to be down there to create @voyage before it can be changed.
  def ensure_user_match
      @voyage = Voyage.find(params[:id])
    if @voyage.captain != current_user
      not_found
    end
  end

  def captain_is_user?(captain_id)
   if current_user
     captain_id == current_user.id
   end
  end

private
  def voyage_params
    params.require(:voyage).permit(:title, :location, :description, :vessel_type, :boat_image_file,:voyage_image_file,:start_time, :end_time, :capacity) #will need to add more fields as they are added to model. , add :captain_id later once it's populated
  end

end

app/helpers/voyages_helper.rb
module VoyagesHelper
end

app/views/voyages/_form.html.erb
<section class="voyage-new-edit all-form-text">

<h1>Take the helm. Create a voyage.</h1> </br> </br>

<%= form_for voyage, url: voyages_path, html: { multipart: true } do |f| %>
<!-- form_for user, url: users_path, html: { multipart: true } do -->

  <div class="field" class="form-group">
   <%= f.label :title %>
   <%= f.text_field :title, :class => "form-control", placeholder: "What's your trip called?"  %>
   </div>

   <div class="field" class="form-group">
     <%= f.label :location %>
     <%= f.text_field :location, :class => "form-control", placeholder: "What's your point of departure?"   %>
   </div>

  <div class="field" class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "form-control", placeholder: "Why should a passenger take this voyage with you? Where will you go? What will you do? Be convincing!"  %>
  </div>

  <div>
    <%= f.label :start_time %>
    <%= f.datetime_field :start_time %>
  </div>

  <div>
    <%= f.label :end_time %>
    <%= f.datetime_field :end_time %>
  </div>

  <div>
    <%= f.label :capacity%>
    <%= f.select :capacity, options_for_select(0..20) %>
  </div>

  <div>
    <%= f.label :vessel_type %>
    <%= f.select :vessel_type, options_for_select([['Keelboat','Keelboat'], ['Dinghy','Dinghy'],['Canoe','Canoe'],['Kayak ','Kayak'],['Motorboat ','Motorboat'],['Jetski','Jetski'],['Catamaran','Catamaran']]) %>
  </div>

  <div class="form-group">
    <%= f.label :boat_image_file, class: "control-label" %>
      <div class="btn btn-blue btn-file">
        Choose Image
        <%= f.file_field :boat_image_file %>
      </div>
  </div>

  <div class="form-group">
    <%= f.label :voyage_image_file, class: "control-label" %>
      <div class="btn btn-blue btn-file">
        Choose Image
        <%= f.file_field :voyage_image_file %>
      </div>
  </div> </br>

  <div>
    <%= f.submit 'Submit', :class => 'btn btn-primary'  %>
  </div>

  <% end %>

</section>

app/views/voyages/_voyage.html.erb
<!-- DO NOT USE THIS FILE RIGHT NOW -->

<div class="voyage-index">
    <h6>Voyage departs from: <%= voyage.location %></h6>
    <h6>Voyage start time: <%= voyage.start_time %></h6>
    <h6>Voyage end time: <%= voyage.end_time %></h6>
    <h6>Voyage description: <%= voyage.description %></h6>
    <h6>Vessel type: <%= voyage.vessel_type %></h6>
    <h6>Boat image: <%= voyage.boat_image_file.url %></h6>
</div>


<section id="services" class="services bg-primary">
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-10 col-lg-offset-1">
<h1><%= @voyage.title %></h1>

<h6>Voyage departs from: <%= @voyage.location %></h6>
<h6>Latitude: <%= @voyage.latitude %></h6>
<h6>Longitude: <%= @voyage.longitude %></h6>
<h6>Voyage start time: <%= @voyage.start_time %></h6>
<h6>Voyage end time: <%= @voyage.end_time %></h6>
<h6>Voyage description: <%= @voyage.description %></h6>
<h6>Vessel type: <%= @voyage.vessel_type %></h6>
<h6>Boat image: <%= image_tag(@voyage.boat_image_file.url) %></h6>
<h6>Voyage capacity: <%= @voyage.capacity %></h6>


</div>
</div>
</div>
</section>
<div id="map"></div>

<script>

  function initMap() {
    var myLatLng = {lat: <%= @voyage.latitude %>, lng: <%= @voyage.longitude %>};

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 8,
      center: myLatLng
    });

    var marker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      title: 'Hello World!'
    });
  }
</script>

<script>
  function initMap() {
    var myLatLng = {lat: <%= @voyage.latitude %>, lng: <%= @voyage.longitude %>};

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 8,
      center: myLatLng
    });

    var marker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      title: 'Hello World!'
    });
  }
</script>

<script
  src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["google_api_key"] %>&callback=initMap"async defer>
</script>


<button type="submit" id="voyage-button">Check Space</button>

  <div class='modal'>
    <div class='inner-modal'>
      <!-- This is the window that fades in, and is different than the window code that is in the partial
      class here pertains to the modal window that will fadeIn. -->
      <%= form_for [@voyage, @reservation], :html => {:class => 'voyage-form-class', :id => 'reservation-form-id'} do |f|%>
      <button type="button" class="close">x</button>
<!-- Added id to call ajax request on form -->
      <h6>Voyage departs from: <%= @voyage.location %></h6>
      <h6>Voyage start time: <%= @voyage.start_time %></h6>
      <h6>Voyage end time: <%= @voyage.end_time %></h6>
      <h6>Voyage description: <%= @voyage.description %></h6>
      <h6>Vessel type: <%= @voyage.vessel_type %></h6>
      <h6>Boat image: <%= @voyage.boat_image_url %></h6>
      <h6>Seat Location: <%= f.text_field :seat_location, placeholder: "Port or Starboard?" %>


      <h6>Life Jacket Size: <%= f.text_field :life_jacket_size,
      placeholder: "Small, Meduim or Large?" %></h6>
      <h6>Special Needs?: <%= f.text_field :need_accessibility,
            placeholder: "What accomodations do you need?" %></h6>

<!-- where is create reservation button ? -->
      <p>
        <%= f.submit %>
        <% end %>
      </p>
    </div>
  </div>

  <h6><%= link_to 'Edit Voyage', edit_voyage_path(@voyage) %><h6>

  <%= link_to 'Delete', voyage_path(@voyage), method: :delete, data: {confirm: "Are you sure you want to delete the voyage '#{@voyage.title}'? This cannot be undone!"}%>

  <!-- Map -->
  <section id="contact" class="map">
      <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d46190.57183521767!2d-79.41786892280132!3d43.65002540989835!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sGilligan!5e0!3m2!1sen!2sca!4v1475676955621></iframe>
      <br />
      <small>
          <a href=https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d46190.57183521767!2d-79.41786892280132!3d43.65002540989835!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sGilligan!5e0!3m2!1sen!2sca!4v1475676955621"></a>
      </small>
      </iframe>
  </section>

  <!-- Footer -->
  <footer>
      <div class="container">
          <div class="row">
              <div class="col-lg-10 col-lg-offset-1 text-center">
                  <h4><strong>Gilligan Boating</strong>
                  </h4>
                  <p>123 Bitmaker Blvd
                      <br>Toronto, ON</p>
                  <ul class="list-unstyled">
                      <li><i class="fa fa-phone fa-fw"></i> (123) 456-7890</li>
                      <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:boating@gilligan.com">boating@gilligan.com</a>
                      </li>
                  </ul>
                  <br>
                  <ul class="list-inline">
                      <li>
                          <a href="#"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                      </li>
                      <li>
                          <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                      </li>
                      <li>
                          <a href="#"><i class="fa fa-dribbble fa-fw fa-3x"></i></a>
                      </li>
                  </ul>
                  <hr class="small">
                  <p class="text-muted">Copyright &copy; Gilligan Boating 2014</p>
              </div>
          </div>
      </div>
      <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
  </footer>

  <!-- Custom Theme JavaScript -->
  <script>
  // Closes the sidebar menu
  $("#menu-close").click(function(e) {
      e.preventDefault();
      $("#sidebar-wrapper").toggleClass("active");
  });
  // Opens the sidebar menu
  $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#sidebar-wrapper").toggleClass("active");
  });
  // Scrolls to the selected menu item on the page
  $(function() {
      $('a[href*=#]:not([href=#],[data-toggle],[data-target],[data-slide])').click(function() {
          if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
              if (target.length) {
                  $('html,body').animate({
                      scrollTop: target.offset().top
                  }, 1000);
                  return false;
              }
          }
      });
  });
  //#to-top button appears after scrolling
  var fixed = false;
  $(document).scroll(function() {
      if ($(this).scrollTop() > 250) {
          if (!fixed) {
              fixed = true;
              // $('#to-top').css({position:'fixed', display:'block'});
              $('#to-top').show("slow", function() {
                  $('#to-top').css({
                      position: 'fixed',
                      display: 'block'
                  });
              });
          }
      } else {
          if (fixed) {
              fixed = false;
              $('#to-top').hide("slow", function() {
                  $('#to-top').css({
                      display: 'none'
                  });
              });
          }
      }
  });
  // Disable Google Maps scrolling
  // See http://stackoverflow.com/a/25904582/1607849
  // Disable scroll zooming and bind back the click event
  var onMapMouseleaveHandler = function(event) {
      var that = $(this);
      that.on('click', onMapClickHandler);
      that.off('mouseleave', onMapMouseleaveHandler);
      that.find('iframe').css("pointer-events", "none");
  }
  var onMapClickHandler = function(event) {
          var that = $(this);
          // Disable the click handler until the user leaves the map area
          that.off('click', onMapClickHandler);
          // Enable scrolling zoom
          that.find('iframe').css("pointer-events", "auto");
          // Handle the mouse leave event
          that.on('mouseleave', onMapMouseleaveHandler);
      }
      // Enable map zooming with mouse scroll when the user clicks the map
  $('.map').on('click', onMapClickHandler);
  </script>

app/views/voyages/edit.html.erb
<h1>Edit Your Voyage</h1>


<section class="voyage-new-edit all-form-text">
<%= form_for [@user, @voyage] do |f| %>
<!-- form_for user, url: users_path, html: { multipart: true } do -->

  <div class="field" class="form-group">
   <%= f.label :title %>
   <%= f.text_field :title, :class => "form-control"  %>
   </div>

  <div"field" class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "form-control"  %>
  </div>

  <div"field" class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, :class => "form-control"   %>
  </div>

  <div>
    <%= f.label :vessel_type %>
    <%= f.select :vessel_type, options_for_select([['Keelboat','Keelboat'], ['Dinghy','Dinghy'],['Canoe','Canoe'],['Kayak ','Kayak'],['Motorboat ','Motorboat'],['Jetski','Jetski'],['Catamaran','Catamaran']]) %>
  </div>

  <div>
    <%= f.label :boat_image_file %>
    <%= f.file_field :boat_image_file %>
  </div>

  <div>
    <%= f.label :voyage_image_file %>
    <%= f.file_field :voyage_image_file %>
  </div>

  <div>
    <%= f.label :start_time %>
    <%= f.datetime_field :start_time %>
  </div>

  <div>
    <%= f.label :end_time %>
    <%= f.datetime_field :end_time %>
  </div>

  <div>
    <%= f.label :capacity%>
    <%= f.select :capacity, options_for_select(0..20) %>
  </div>

    <%= f.submit %>
  <% end %>
</section>

app/views/voyages/index.html.erb
<!-- Header -->

  <div id="search-bar">
    <%= form_tag(voyages_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search by location", class: 'form-control' %>
      <span class="input-group-btn">
    <%= submit_tag "Search", class: 'btn btn-default'  %>
      </span>
    <% end %>
  </div>


<header id="top" class="header">
    <div class="text-vertical-center">

        <h1>Gilligan</h1>
        <h3>Coming soon to a dock near you</h3>
        <br>
        <a href="#about" class="btn btn-dark btn-lg">Find Out More</a>


    </div>
</header>

<!-- About -->
<section id="about" class="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Get on the water without owning your own boat!</h2>
                <p class="lead">Connect with boaters in your community today.</p>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

<!-- Services -->
<!-- The circle icons use Font Awesome's stacked icon classes. For more information, visit http://fontawesome.io/examples/ -->
<section id="services" class="services bg-primary">
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-10 col-lg-offset-1">
                <h2>Welcome Aboard!</h2>
                <hr class="small">
                <div class="row">
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span class="fa-stack fa-4x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-anchor fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Connect with boat owners</strong>
                            </h4>
                            <p>Here captains and landlubbers can all find each other.</p>
                            <a href="#" class="btn btn-light">Learn More</a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span class="fa-stack fa-4x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-medkit fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Safe Journey Guaranteed</strong>
                            </h4>
                            <p>Our captains and mates are all trained in safety and first aid.</p>
                            <a href="#" class="btn btn-light">Learn More</a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span class="fa-stack fa-4x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-smile-o fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Free To Use</strong>
                            </h4>
                            <p>We don't charge any fees, so you're free to sail the seventh seas.</p>
                            <a href="#" class="btn btn-light">Learn More</a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span class="fa-stack fa-4x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-calendar fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Anytime, anywhere</strong>
                            </h4>
                            <p>Anywhere on the globe, ahoy, and you're off on a tub</p>
                            <a href="#" class="btn btn-light">Learn More</a>
                        </div>
                    </div>
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.col-lg-10 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

<!-- Callout -->
<aside class="callout">
    <div class="text-vertical-center">
        <h1>Goodbye city. Hello fresh air.</h1>
    </div>
</aside>

<!-- Portfolio -->
<section id="portfolio" class="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1 text-center">
                <h1>Become a captain. </h1>
                <h3> <%= link_to "Create your voyage today", new_voyage_path  %> </h3> </br> </br>
                  <h1>Need a ride? Choose a Voyage</h1>

                <hr class="small">
                <div class="row">
                  <% @voyages.each do |voyage|%>
                    <div class="col-md-6">
                        <div class="portfolio-item">

<!-- sntax ("/icons/icon.gif", height: '32', width: '32', class: "") -->
                        <h3> <%= voyage.title %> </h3>
                      <%= link_to image_tag(voyage.voyage_image_file.url,  class:'img-portfolio img-responsive'), voyage %>
                    </div>
                  </div>
                  <%end%>

                </div>
                <!-- /.row (nested) -->
                <a href="#" class="btn btn-dark">View More Items</a>
            </div>
            <!-- /.col-lg-10 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

<!-- Call to Action -->
<aside class="call-to-action bg-primary">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h3>Ready for adventure?</h3>
                 <a href="<%= login_path %>" class="btn btn-lg btn-light">Log in</a>
                <a href="<%= new_user_path %>" class="btn btn-lg btn-dark">Sign up Now!</a>
            </div>




        </div>
    </div>
</aside>

app/views/voyages/new.html.erb
<%= render 'form', voyage: @voyage, reservation: @reservation %>

app/views/voyages/show.html.erb
<div class="row">

<!-- make more general class names -->
  <section class="col-xs-12 page-show-header" style="background-image: url(<%= @voyage.voyage_image_file.url%>)" ></section>

  <section class="col-xs-12 col-sm-6 page-details-section">

    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>



    <h1><%= @voyage.title %></h1>
    <h5>Voyage departs from: <%= @voyage.location %></h5>
    <h5>Voyage start time: <%= @voyage.start_time.strftime("%I %b,%Y %I:%M%P") %></h5>
    <h5>Voyage end time: <%= @voyage.end_time.strftime("%I %b,%Y %I:%M%P") %></h5>
    <h5>Voyage description: <%= @voyage.description %></h5>
    <h5>Vessel type: <%= @voyage.vessel_type %></h5>
    <h5>Voyage capacity: <%= @voyage.capacity %></h5>

</section>

<section class="col-xs-12 col-sm-6 page-images-section">
  <%= image_tag(@voyage.boat_image_file.url) %>


</section>
  <% if captain_is_user?(@voyage.captain_id) == false %>
<section class="col-xs-12 page-show-button">
    <h3>Book your reservation now</h3>
    <!-- add possible last resvertation made -->
    <!-- maybe a possible clock downtown unitl voyage time -->
  <button type="submit" id="voyage-button">Check Space</button>

</section>
  <% end %>


  <section class="col-xs-12 voyage-map-section">
      <div id="map" class="overlay">
        <script id="map-div">

          function initMap() {
            var myLatLng = {lat: <%= @voyage.latitude %>, lng: <%= @voyage.longitude %>};

            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 10,
              center: myLatLng
            });

            var marker = new google.maps.Marker({
              position: myLatLng,
              map: map,
              title: 'Hello World!'
            });
          }
    </script>
  </div>

    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["google_api_key"] %>&callback=initMap" async defer></script>

    <!-- <section id="contact" class="map">
        <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d46190.57183521767!2d-79.41786892280132!3d43.65002540989835!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sGilligan!5e0!3m2!1sen!2sca!4v1475676955621></iframe>
        <br />
        <small>
            <a href=https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d46190.57183521767!2d-79.41786892280132!3d43.65002540989835!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sGilligan!5e0!3m2!1sen!2sca!4v1475676955621"></a>
        </small>
        </iframe>
    </section> -->



  </section>


</div>


  <div class='modal'>
    <div class='inner-modal'>
      <!-- This is the window that fades in, and is different than the window code that is in the partial
      class here pertains to the modal window that will fadeIn. -->
      <%= form_for [@voyage, @reservation], :html => {:class => 'voyage-form-class create-res-modal', :id => @voyage.id } do |f|%>
      <button type="button" class="close">x</button>
<!-- Added id to call ajax request on form -->
      <h6>Voyage departs from: <%= @voyage.location %></h6>
      <h6>Voyage start time: <%= @voyage.start_time %></h6>
      <h6>Voyage end time: <%= @voyage.end_time %></h6>
      <h6>Vessel type: <%= @voyage.vessel_type %></h6>
      <h6>Seat Location: <%= f.text_field :seat_location, placeholder: "port or starboard?" %>
      <h6>Life Jacket Size: <%= f.text_field :life_jacket_size,
      placeholder: "small, meduim of large" %></h6>
      <h6>Special Needs?: <%= f.text_field :need_accessibility,
            placeholder: "what you need?" %></h6>
      <h3 id='seats-left'><%=  @voyage.present_capacity %></h3>
<!-- where is create reservation button ? -->
      <p>
        <%= f.submit %>
        <% end %>
      </p>
    </div>
  </div>

app/views/voyages/update.html.erb
<h1>Voyages#update</h1>
<p>Find me in app/views/voyages/update.html.erb</p>