config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/edit'

  get 'password_resets/update'

 root 'voyages#index'
 resources :user_sessions
 resources :users

 resources :voyages do
   resources :reservations
 end

 get 'login' => 'user_sessions#new', :as => :login
 delete 'logout' => 'user_sessions#destroy', :as => :logout

 resources :password_resets

end
#destroy', :as => :logout

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  # perhaps this shoudl be voyage_id as a foreign_key?
    has_many :voyages, foreign_key: :captain_id
    # validates_presence_of :name
    has_many :reservations, foreign_key: :passenger_id

    has_attached_file :user_image_file, default_url: "missing.png"
     validates_attachment_content_type :user_image_file, content_type: /\Aimage\/.*\z/
    #
    validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
    validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
    validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
    #
    # validates :email, uniqueness: true
    validates :email, length: {minimum: 5}
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

    validates :name, presence: true
    validates :name, length: { minimum: 2}


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  #
  skip_before_action :require_login, only: [:index, :new, :create]

# This is here only becuase maybe the user page need the voyage info? So far it has not.
  # before_action do
  #   @voyage = Voyage.find(params[:voyage_id]) if params[:voyage_id]
  # end
  # GET /users
  # GET /users.json
  def index
  @user = User.find(params[:id])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    if @user == current_user

    else
      redirect_to root_path
    end


    @reservation = @user.reservations
    # find(params[:id])
    # @voyages = User.voyages
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      redirect_to(:voyages, notice: 'User was successfully created') #redirects user to index
    end
    respond_to do |format|
      if @user.save
        format.html {  }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :bio, :password, :password_confirmation, :user_image_file)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<section class="all-form-text all-sign-up-box">


<%= form_for user, html: { multipart: true } do |f| %>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    <% end %>
    </div>


  <div class="field" class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, placeholder: "Full Name", :class => "form-control" %>
  </div>

  <div class="field" class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, placeholder: "Email", :class => "form-control" %>
  </div>

  <div class="field" class="form-group">
   <%= f.label :password %><br />
   <%= f.password_field :password, placeholder: "Create password", :class => "form-control" %>
 </div>

 <div class="field" class="form-group">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation, placeholder: "Confirm password", :class => "form-control" %>
 </div>

  <div class="field" class="form-group">
    <%= f.label :bio %>
    <%= f.text_area :bio, placeholder: "Tell us about your boating experience! (Optional)", :class => "form-control"%>
  </div>

    <div class="form-group field">
     <%= f.label :user_image_file, class: "control-label" %>
       <div class="btn btn-blue btn-file">
         Choose Profile Image
         <%= f.file_field :user_image_file %>
       </div>
    </div>



  <div class="actions field">
    <%= f.submit 'Submit', :class => 'btn btn-primary'  %>
  </div>

<% end %>

<h6><%= link_to 'Back',  new_user_session_path %></h6>
</section>

app/views/users/_user.html.erb
     <div class="row">
     <!-- make more general class names -->

     <section class="col-xs-12 page-show-header" style="background-image: url(http://www.ask2travel.com/wp-content/uploads/2016/07/%CE%99%CE%A3%CE%A4%CE%99%CE%9F%CE%A0%CE%9B%CE%9F%CE%8A%CE%91.png)">


     </section>

       <section class="col-xs-12 col-sm-6 page-details-section">
         <h2><%= user.name %>'s Profile </h2>

           <div class='user-name-div'>

            <h4><%= user.name %>'s email: <%= user.email %></h4>
           </div>
           <h3><%= link_to "Click to Edit User", edit_user_path %>
         <h3>All Reservations</h3>
           <% user.reservations.each do |reservation|%>
           <h6>Reservation Confirmation No. <%=  reservation.id %> </h6>
           <h6>Voyage Title: <%= reservation.voyage.title %></h6>
           <h6><%= link_to "Click to View this Voyage:", voyage_path(reservation.voyage_id) %></h6>
             <h5><%= link_to 'Click to Delete Reservation',voyage_reservation_path(reservation.voyage_id, reservation.id), method: :delete, data: {confirm: "Are you sure you want to delete this reservation # '#{reservation.id}'? This cannot be undone!"} %></h5>
           <hr>
         <% end %>

     </section>

     <section class="col-xs-12 col-sm-6 page-images-section">
       <%= image_tag(@user.user_image_file.url) %>

     </section>
       <section class="col-xs-12 voyage-map-section all-form-text">

         <h2>All My Created Voyages </h2>
         <% user.voyages.each do |voyage| %>
         <h4>Voyage Title: <%= voyage.title %></h4>
         <h4>Voyage Location: <%= voyage.location %></h4>
         <h4>Voyage Desctiption: <%= voyage.description %></h4>
         <h5><%= link_to "Click to View Voyage", voyage_path(voyage) %></h5>
         <h5><%= link_to 'Click to Edit Voyage', edit_voyage_path(voyage) %><h5>
         <h5><%= link_to 'Click to Delete Voyage', voyage_path(voyage), method: :delete, data: {confirm: "Are you sure you want to delete the voyage '#{voyage.title}'? This cannot be undone!"} %></h5>
<hr>
         <% end %>



         <h3>All passengers on this Voyage</h3>
         <% user.voyages.each do |voyage| %>
         <% voyage.passengers.each do |passenger| %>
         <h4>Passenger Name: <%= passenger.name %></h4>
         <h6>Passenger Info:<%= passenger.bio %></h6>
         <% end %>
         <% end %>
       </section>

     </div>

app/views/users/edit.html.erb
<h1 id="edit-user-header">Edit your Profile</h1>


<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h2>Users</h2>


<div class="users-display">

    <% @users.each do |user|%>
    <%= render 'user', user: user%>
    <% end %>
  </div>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h2 id="user-new-h2">All Aboard! Sign up now.</h2>

<%= render 'form', user: @user %>

<!-- Move back link to partial -->

app/views/users/show.html.erb
<%= render 'user', user: @user %>