config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/edit'

  get 'password_resets/update'

 root 'voyages#index'
 resources :user_sessions
 resources :users

 resources :voyages do
   resources :reservations
 end

 get 'login' => 'user_sessions#new', :as => :login
 delete 'logout' => 'user_sessions#destroy', :as => :logout

 resources :password_resets

end
#destroy', :as => :logout

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
     @user = User.new
   end

   def create
     if @user = login(params[:email], params[:password])
       redirect_back_or_to(:voyages, notice: 'Login successful')
       
  # made changes to redirect to voyages

     else
       flash.now[:alert] = 'Login failed'
       render action: 'new'
     end
   end

   def destroy
     logout
     redirect_to(:voyages, notice: 'Logged out!')
     #made changes to redirect to voyages
   end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_forgot_password_form.html.erb
<section ="all-form-text reset-password-bkg">

  <h1> Reset Password!! </h1>

<%= form_tag password_resets_path, :method => :post do %>

  <div class="field" class="form-group">
    <%= label_tag :email %> <br/>
    <%= text_field_tag :email, :class => "form-control" %>

    <%= submit_tag "Reset my PASSWORD!!!", :class => 'btn btn-primary' %>
  </div>

<% end %>
</section>

app/views/user_sessions/_form.html.erb
<section class="all-form-text login-all ">

  <div class="login-bkg">

    <div class="log-in-page-text">

      <h1>Sign in to Gilligan</h1>

<%= form_tag user_sessions_path,
  :method => :post,
  id: "login-form" do %>

<!-- <div class="form-group">
   <label for="exampleInputEmail1">Email address</label>
   <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
   <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
 </div> -->

  <div class="field" class="form-group">
    <%= label_tag :email %><br />
    <%= text_field_tag :email, "", :class => "form-control" %>
  </div>
  <div class="field" class="form-group">
    <%= label_tag :password %><br/>
    <%= password_field_tag :password, "", :class => "form-control" %>
  </div>
  <div class="actions">
    <%= submit_tag "Login", :class => 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Forgot Password?', new_password_reset_path %>
    </div>
  </div>
</section>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<%= render 'form' %>

<!-- Link to forgot password in partial -->