config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/edit'

  get 'password_resets/update'

 root 'voyages#index'
 resources :user_sessions
 resources :users

 resources :voyages do
   resources :reservations
 end

 get 'login' => 'user_sessions#new', :as => :login
 delete 'logout' => 'user_sessions#destroy', :as => :logout

 resources :password_resets

end
#destroy', :as => :logout

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gilligan</title>
  <%= stylesheet_link_tag '' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

      <!-- Navigation -->
      <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
      <nav id="sidebar-wrapper">
          <ul class="sidebar-nav">
              <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
              <li class="sidebar-brand">
                  <a href="#top" onclick=$("#menu-close").click();>Navigation</a>
              </li>
              <li>
                  <a href="<%= root_path %>" onclick=$("#menu-close").click();>Home</a>
              </li>

             <% if logged_in?  %>

              <li>
                   <a href="<%= user_path (current_user.id) %>"  onclick=$("#menu-close").click();>Profile</a>
              </li>

              <% end %>

              <li>
                  <a href="<%= root_path %>#portfolio" onclick=$("#menu-close").click();>Choose a Voyage</a>
              </li>



              <li>
                  <a href="<%= new_voyage_path %>" onclick=$("#menu-close").click();>Create a Voyage</a>
              </li>



             <% if logged_in?  %>

             <li>
               <%= link_to("Log Out", logout_path, :method => :delete) %>
             </li>

             <% else %>

              <li>
                  <a href="<%= login_path %>" onclick=$("#menu-close").click();>Log In</a>
              </li>

              <li>
                  <a href="<%= new_user_path %>" onclick=$("#menu-close").click();>Sign-Up</a>
              </li>
            <% end %>



          </ul>
      </nav>

      <!-- Header -->


      <!-- About -->

      <!-- Callout -->


      <!-- Portfolio -->

<!-- sntax ("/icons/icon.gif", height: '32', width: '32', class: "") -->
<% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>




<main class ="<%= controller.controller_name %> <%= controller.action_name %>">

  <%= yield %>

</main>
      <!-- Footer -->
      <footer>
          <div class="container">
              <div class="row">
                  <div class="col-lg-10 col-lg-offset-1 text-center nautical_footer">
                      <h4><strong>Gilligan Adventures</strong>
                      </h4>
                      <p>123 Bitmaker Blvd
                          <br>Toronto, ON</p>
                      <ul class="list-unstyled">
                          <li><i class="fa fa-phone fa-fw"></i> (123) 456-7890</li>
                          <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:boating@gilligan.com">boating@gilligan.com</a>
                          </li>
                      </ul>
                      <br>
                      <ul class="list-inline">
                          <li>
                              <a href="#"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                          </li>
                          <li>
                              <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                          </li>
                          <li>
                              <a href="#"><i class="fa fa-vine fa-fw fa-3x"></i></a>
                          </li>
                      </ul>
                      <hr class="small">
                      <p class="text-muted">Copyright &copy; Gilligan Adventures 2016</p>
                  </div>
              </div>
          </div>
          <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
      </footer>